name: nightly

on:
  schedule:
  - cron: "0 0 * * *"
  # Manual dispatch, only for testing purposses
  # See https://docs.github.com/en/actions/managing-workflow-runs/manually-running-a-workflow
  workflow_dispatch:

jobs:
  nightly:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0

      # Get tag
      - name: Add upstream repository
        run: |
          git remote add versatica https://github.com/versatica/mediasoup.git
          git remote update --prune
      - name: 'Get Previous tag'
        id: previoustag
        uses: "WyriHaximus/github-action-get-previous-tag@v1"

      # Merge and re-tag
      - name: Config git user name and email
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
      - name: Merge
        run: |
          git merge "${{ steps.previoustag.outputs.tag }}"
          git checkout --theirs package.json
          git checkout --theirs package-lock.json
      - name: Fix package name
        run: |
          jq '.name = "@mafalda/mediasoup"' package.json > package.json.tmp
          mv package.json.tmp package.json

          jq '(.name, .packages[""].name) |= "@mafalda/mediasoup"' package-lock.json > package-lock.json.tmp
          mv package-lock.json.tmp package-lock.json

          git add package.json package-lock.json
          git commit --amend --no-edit package.json package-lock.json
      - name: Tag and push
        run: |
          git push
          git tag --force "${{ steps.previoustag.outputs.tag }}"
          git push --force --tags
